@startuml ExoMVC_v27

skinparam ClassFontSize 11
skinparam ClassFontName Verdana


together {
    abstract class GetAndPostCleaner {
        #inputCleaner()
    }

    class Launcher extends GetAndPostCleaner {
        -$cleanedUpGet : array
        -$cleanedUpPost : array
        -$selectedController : string
        --
        +__construct()
        -launcher()
    }

    class Autoloader {
        {static} +register()
        {static} -autoload()
    }
}


together {
    package controller #6A89A5 {
        class HomeGetController {
            -$homeModel : obj
            -$homeView : obj
            --
            +__construct()
            +displayHomePage()
        }

        package category {
            abstract class CategoryCommonController {
                #$categoryModel : obj
                --
                #instanciateModel()
            }

            class CategoryGetController extends CategoryCommonController {
                +actionReceiver()
                -displayAllCategories()
            }

            class CategoryPostController extends CategoryCommonController {
                +actionReceiver()
            }
        }

        package client {
            abstract class ClientCommonController {
                #$clientModel : obj
                --
                #instanciateModel()
            }

            class ClientGetController extends ClientCommonController {
                +actionReceiver()
                -displayClientPage()
            }

            class ClientPostController extends ClientCommonController {
                +actionReceiver()
            }

        }

        package prospect {
            abstract class ProspectCommonController {
                #$prospectModel : obj
                --
                #instanciateModel()
            }

            class ProspectGetController extends ProspectCommonController {
                +actionReceiver()
                -displayProspPage()
            }

            class ProspectPostController extends ProspectCommonController {
                +actionReceiver()
            }


        }

        package formsChecks {
            class ProspClientFormsChecks {
                +prospClientFormChecks()
            }

            class CatFormsChecks {
                +catFormInputChecks()
            }
        }
    }
}





together {
    package model #6A89A5 {
        abstract class ModelInChief {
            #$dbConnect : obj
            #$query : obj
            --
            +__construct()
            #pdoInit()
            #pdoQueryExecute()
        }

        class HomeModel extends ModelInChief {
            +selectThreeLastProspAndThreeLastClients()
        }

        class ClientModel extends ModelInChief {
            +selectAllClients()
            +addClient()
            +editClient()
            +deleteClient()
        }

        class ProspectModel extends ModelInChief {
            +selectAllProspects()
            +addProspect()
            +editProspect()
            +deleteProspect()
        }

        class CategoryModel extends ModelInChief {
            +selectAllCategories()
            +addCategory()
            +editCategory()
            +deleteCategory()
        }
    }
}





together {
    package view #6A89A5 {
        abstract class ViewInChief {
        #$pageContent : obj
        --
        #pageSetup()
        #tableSetup()
        #pageDisplay()
        }

        class TableBuilder extends ViewInChief {
            {static} +clientAndProspTableRowBuilder()
            {static} +categoryTableRowWithButtonsBuilder()
            {static} +prospAndClientTableRowWithButtonsBuilder()
        }

        package homeview #4277A5 {
            class HomeView extends ViewInChief {
                -$pageSettingsList : array
                --
                +__construct()
                +buildOrder()
                -tableRowsBuilder()
            }
        }

        package prospclientview #4277A5 {
            abstract class ProspClientFormAndTableConfigurator extends ViewInChief {
                #prospClientFormConfigurator()
                #tableRowsBuilder()
            }

            package clientview #3A86C8 {
                abstract class ClientPageAssemblyLine extends ProspClientFormAndTableConfigurator {
                    #pageSettingsListStorage()
                }

                package form_clientview #47aaff {
                    abstract class ClientFormAssemblyLine extends ClientPageAssemblyLine {
                        #formSettingsListStorage()
                    }

                    class ClientFormViewBuilder extends ClientFormAssemblyLine {
                        +buildOrder()
                    }
                }


                package table_clientview #47aaff {
                    abstract class ClientTableAssemblyLine extends ClientPageAssemblyLine {
                        #$tableSettingsList : array
                        --
                        +__construct()
                    }

                    class ClientTableViewBuilder extends ClientTableAssemblyLine {
                        +buildOrder()
                    }
                }
            }

            package prospview #3A86C8 {
                abstract class ProspPageAssemblyLine extends ProspClientFormAndTableConfigurator {
                    #pageSettingsListStorage()
                }

                package form_prospview #47aaff {
                    abstract class ProspFormAssemblyLine extends ProspPageAssemblyLine {
                        #formSettingsListStorage()
                    }

                    class ProspFormViewBuilder extends ProspFormAssemblyLine {
                        +buildOrder()
                    }
                }

                package table_prospview #47aaff {
                    abstract class ProspTableAssemblyLine extends ProspPageAssemblyLine {
                        #$tableSettingsList : array
                        --
                        +__construct()
                    }

                    class ProspTableViewBuilder extends ProspTableAssemblyLine {
                        +buildOrder()
                    }
                }
            }
        }

        package catview #4277A5 {
            abstract class CatPageAssemblyLine extends ViewInChief {
                #pageSettingsListStorage()
            }

            package form_catview #3A86C8 {
                abstract class CatFormAssemblyLine extends CatPageAssemblyLine {
                    #formsSettingsListStorage()
                    #catFormConfigurator()
                }

                class CatFormViewBuilder extends CatFormAssemblyLine {
                    +buildOrder()
                }
            }

            package table_catview #3A86C8 {
                abstract class CatTableAssemblyLine extends CatPageAssemblyLine {
                    #$tableSettingsList : array
                    --
                    +__construct()
                    #tableRowsBuilder()
                }

                class CatTableViewBuilder extends CatTableAssemblyLine {
                    +buildOrder()
                }

            }
        }
    }
}

Launcher -[hidden]--> HomeGetController
GetAndPostCleaner -[hidden]> model
HomeGetController -[hidden]-> formsChecks
formsChecks -[hidden]-> view
ViewInChief -[hidden]> TableBuilder

@enduml