@startuml
skinparam Style strictuml

skinparam ClassFontSize 11
skinparam ClassFontName Verdana

together {
    class Autoloader {
        {static} +register()
        {static} +autoload()
    }

    class Launcher {
        +__construct()
    }

    class InputsManagement {
        {static} +inputCleanup()
    }
}




together {
    package controller #6A89A5 {
        class ControllerInChief {
            #input_cleanup()
            #categoryFormChecks()
            #prospClientFormChecks()
        }

        ControllerInChief <|-- HomeController
        class HomeController {
            -$homeTableView : obj
            -$homeModel : obj
            -$getGather : array
            --
            +__construct()
            +getTableActionFromGet()
        }

        ControllerInChief <|-- ClientController
        class ClientController {
            -$clientTableView : obj
            -$clientFormView : obj
            -$clientModel : obj
            -$getGather : array
            -$postGather : array
            --
            +__construct()
            +getTableActionFromGet()
            +modelMethodLauncher()
            +realGetTable()
            +addActionFromGet()
            +editActionFromGet()
            +deleteActionFromGet()
        }

        ControllerInChief <|-- ProspectController
        class ProspectController {
            -$prospectTableView : obj
            -$prospectFormView : obj
            -$prospectModel : obj
            -$getGather : array
            -$postGather : array
            --
            +__construct()
            +getTableActionFromGet()
            +modelMethodLauncher()
            +realGetTable()
            +addActionFromGet()
            +editActionFromGet()
            +deleteActionFromGet()
        }

        ControllerInChief <|-- CategoryController
        class CategoryController {
            -$categoryTableView : obj
            -$categoryFormView : obj
            -$categoryModel : obj
            -$getGather : array
            -$postGather : array
            --
            +__construct()
            +getTableActionFromGet()
            +modelMethodLauncher()
            +realGetTable()
            +addActionFromGet()
            +editActionFromGet()
            +deleteActionFromGet()
        }
    }
}


together {
    package model #6A89A5 {
        class ModelInChief {
        #$dbConnect : obj
        #$request : array
        --
        +__construct()
        #executeTryCatch()
        }

        ModelInChief <|-- HomeModel
        class HomeModel {
            +homeTableGet()
        }

        ModelInChief <|-- ClientModel
        class ClientModel {
            +getClientTable()
            +add()
            +edit()
            +delete()
        }

        ModelInChief <|-- ProspectModel
        class ProspectModel {
            +getProspTable()
            +add()
            +edit()
            +delete()
        }

        ModelInChief <|-- CategoryModel
        class CategoryModel {
            +catTableGet()
            +add()
            +edit()
            +delete()
        }
    }
}


together {
    package view #6A89A5 {
        class ViewInChief {
        #$pageContent : obj
        --
        +__construct()
        #pageSetup()
        #htmlCharConvert()
        #tableSetup()
        #pageDisplay()
        }

        package homeview #4277A5 {
            ViewInChief <|-- HomeView
            class HomeView {
                #pageSettings()
            }

            HomeView <|-- HomeTableView
            class HomeTableView {
                +tablePrepare()
            }
        }

        package prospclientview #4277A5 {
            ViewInChief <|-- ProspectClientView
            class ProspectClientView {
                #prospClientFormSetup()
            }

            package clientview #3A86C8 {
                ProspectClientView <|-- ClientView
                class ClientView {
                    #pageSettings()
                }

                ClientView <|-- ClientFormView
                class ClientFormView {
                    +addFormSettings()
                    +editFormSettings()
                    +deleteFormSettings()
                }

                ClientView <|-- ClientTableView
                class ClientTableView {
                    +tableSettings()
                    +tablePrepare()
                }
            }

            package prospview #3A86C8 {
                ProspectClientView <|-- ProspectView
                class ProspectView {
                    #pageSettings()
                }

                ProspectView <|-- ProspectFormView
                class ProspectFormView {
                    +addFormSettings()
                    +editFormSettings()
                    +deleteFormSettings()
                }

                ProspectView <|-- ProspectTableView
                class ProspectTableView {
                    +tableSettings()
                    +tablePrepare()
                }
            }
        }

        package catview #4277A5 {
            ViewInChief <|-- CategoryView
            class CategoryView {
                #pageSettings()
            }

            CategoryView <|-- CategoryFormView
            class CategoryFormView {
                +addFormSettings()
                +editFormSettings()
                +deleteFormSettings()
                +catFormSetup()
            }

            CategoryView <|-- CategoryTableView
            class CategoryTableView {
                +tableSettings()
                +catTablePrepare()
            }
        }
    }
}

ControllerInChief -[hidden] ModelInChief
ControllerInChief -[hidden]--> ViewInChief

@enduml